language: go
dist: xenial
sudo: true
services:
- docker
env:
  matrix:
  - GO111MODULE=on
matrix:
  allow_failures:
  - go: master
  include:
  - os: linux
    go: 1.12.x
    cache:
      directories:
      - "/home/travis/.cache/go-build"
  - os: linux
    go: master
  - os: osx
    go: 1.12.x
    cache:
      directories:
      - "/Users/travis/Library/Caches/go-build"
  # - os: windows
  #   go: 1.12.x
before_install:
- GO111MODULE=off go get -u github.com/client9/misspell/cmd/misspell
- GO111MODULE=off go get -u golang.org/x/lint/golint
- GO111MODULE=off go get github.com/fzipp/gocyclo
- GO111MODULE=off go get -u honnef.co/go/tools/cmd/staticcheck
- GO111MODULE=off go get golang.org/x/tools/cmd/cover
before_script:
- GOFILES=$(find . -type f -name '*.go' | grep -v vendor | grep -v client)
script:
# Just check gofmt on linux, it's the fastest builder
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
- go test ./... -race -coverprofile=coverage.txt -covermode=atomic
- misspell -error -locale US $GOFILES
- gocyclo -over 20 $GOFILES
- golint -set_exit_status $GOFILES
- staticcheck ./cmd/ofactest/*.go
- staticcheck ./cmd/server/*.go
- staticcheck ./internal/database/*.go
- staticcheck *.go
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH";fi
after_success:
- bash <(curl -s https://codecov.io/bash) -X fix
- make
- make client
- make docker
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: lPJQJFPgzw0eAZwG6A5yG3hMVrkuAeXhZy0wcWpOHWH/Ten2uDPo0hm4W5aoeTLi0ABEL9YWeheZRtq5BY9sxNBZLoGf4duz9q4Nc+WvrJT7dIEaynbK1ou2ycHPU35VX3FY6wdcCBPxcDVNQiKHgreXpY6IbcBj8iDWYaaz945INoN+8LAkceyeonrm7AeqeS2jEmdbxlOAHxGFh2mgP2XylLAIKrWe/tvOEPvn7Hz/EIjTJE7K5+j+UhNFFUd+VtcN8I/qyPrs9IoleIKrU9lx1RcrXA0EPDt+bXFzc233Uwa5lYBsj3mtI1imriCEy9ByA8CEBwYOxa9KQPendkGlwqGrKn3bjDXKuBKM7nsiJWG4uHUABMQGBVDXGXcOJnDsmcaR69sCrNxFWed8R4YpYC/QLZkNVPnw4E08dQ9gaw83I6mUW01/qeFczgDd/HDjhNRB1o6/y4Jb5kPVTRYiQ8p+suAmhPfmIUOKlSjwBTB95LisrWtEud66tzfkV9XdKvuxh0FYdlIGDhexcUEME7ZkYo5gelDPmX4V5NagBmKd+9Y+xYAsqCE/Z3Vy0DWRyGZYZGxWcQ5+8M0XlYrPqBP6saDALM8XI+apNuLa3KKzozS5s4G2F9vSVyFHOS+uhOnAz6gftrL9t6g2E9KHiN43tf2JhNrsVNqZbEs=
  file_glob: true
  file:
    - bin/ofac-*
  on:
    repo: moov-io/ofac
    tags: true
    go: 1.12.x
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
